export { default as InputText } from './InputText.vue'
export { default as InputDate } from './InputDate.vue'
export { default as InputLocation } from './InputLocation.vue'
export { default as InputImage } from './InputImage.vue'
export { default as InputImageMultiple } from './InputImageMultiple.vue'
export { default as InputRadioGroup } from './InputRadioGroup.vue'
export { default as InputSelect } from './InputSelect.vue'
